
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 44
#define YY_END_OF_BUFFER 45
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[273] =
    {   0,
        0,    0,   45,   44,   35,   34,   27,   26,   44,   42,
       40,   31,   30,   32,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   28,
       29,   33,   35,    0,   42,   42,   40,   38,   42,   41,
       43,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   36,   41,
       41,   41,   41,   41,    0,   42,   41,   37,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   25,   42,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,

       41,   41,   41,   41,   18,   41,   41,   41,   42,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   11,
       41,   41,   41,   41,   41,   41,   41,   24,   42,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       15,   41,   41,   19,   41,   39,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   16,   17,   41,   41,
       41,   41,    3,   41,   41,   41,   41,    8,   41,   41,
       41,   41,   41,   41,   41,    1,   41,   41,   41,   41,

       41,    9,   41,   41,   41,   41,   41,   41,   41,    4,
        5,   41,    7,   41,   41,   41,   41,   20,   41,   41,
       41,   10,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,    2,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   14,
       41,   41,   41,   41,   12,   41,   41,   41,   41,   41,
       41,   41,   41,   21,   41,   41,   23,   41,    6,   13,
       22,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    8,    9,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   11,   12,    1,
       13,    1,    1,    1,   14,   15,   14,   16,   17,   14,
       18,   14,   14,   14,   19,   20,   21,   14,   22,   23,
       14,   14,   24,   25,   14,   14,   14,   14,   14,   14,
        1,    1,    1,    1,   26,    1,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   14,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,    1,   53,   54,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[55] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    3,    3,    3,
        4,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    2,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[278] =
    {   0,
        0,    0,  128, 1536,  115, 1536, 1536, 1536,   66,    0,
       47, 1536, 1536, 1536,   52,   62,   73,   78,   84,   94,
      107,  100,  128,  133,  139,  144,  164,  177,  185, 1536,
     1536, 1536,  104,   51,    0,   73,  191,    0,  112,  208,
        0,   67,  213,  218,  229,  238,  243,  249,  263,  270,
      275,  284,  300,  305,  310,  321,  331,  337,  342,  347,
      363,  371,  376,  383,   42,   48,  399,  404,  411,  420,
      431,  436,  441,  447,  457,  473,  478,  485,  494,  499,
      510,  515,  521,  537,  542,  550,  562, 1536,   62,  570,
      576,  583,  590,  254,  596,  603,  610,  619,  630,  639,

      650,  660,  666,  673,  689,  694,   89,  701,  114,  715,
      710,  722,  731,  295,  154,  751,  756,  764,  173,  772,
      777,  793,  798,  804,  809,  818,  392,  825,   57,  834,
      839,  845,  316,  425,  855,  865,  870,  530,  875,  785,
      886,  891,  897,  907,  743,   54,  625,  913,  921,  881,
      927,  452,  933,  936,  680,  941,  946,  952,  223,  955,
      966,  960,  814,  977,  980,  989,  850,  994,  997, 1000,
     1012, 1018, 1005, 1021, 1034, 1046, 1049, 1054, 1041, 1062,
     1065, 1070, 1076, 1083, 1086, 1096, 1099, 1102, 1108, 1111,
     1114, 1119, 1126, 1129, 1134, 1139, 1146, 1149, 1152, 1155,

     1161, 1165, 1168, 1175, 1178, 1181, 1186, 1191, 1194, 1197,
     1203, 1214, 1222, 1225, 1228, 1231, 1236, 1239, 1242, 1245,
     1248, 1251, 1257, 1264, 1269, 1272, 1275, 1283, 1289, 1292,
     1303, 1307, 1314, 1317, 1320, 1323, 1330, 1333, 1336, 1339,
     1342, 1348, 1355, 1362, 1372, 1375, 1383, 1386, 1389, 1395,
     1398, 1404, 1409, 1413, 1416, 1421, 1428, 1431, 1442, 1445,
     1453, 1456, 1459, 1462, 1469, 1472, 1475, 1479, 1494, 1497,
     1500, 1536, 1522, 1524, 1527, 1529, 1532
    } ;

static yyconst flex_int16_t yy_def[278] =
    {   0,
      272,    1,  272,  272,  272,  272,  272,  272,  272,  273,
      273,  272,  272,  272,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  272,
      272,  272,  272,  272,  273,  273,  273,  273,  275,  274,
      276,  277,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  272,  273,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  272,  273,  274,
      274,  274,  274,  277,  274,  274,  274,  274,  274,  274,

      274,  274,  274,  274,  274,  274,  277,  274,  273,  274,
      274,  274,  274,  277,  277,  274,  274,  274,  277,  274,
      274,  274,  274,  274,  274,  274,  277,  274,  273,  274,
      274,  274,  277,  277,  274,  274,  277,  277,  274,  277,
      274,  274,  274,  274,  277,  273,  277,  274,  274,  277,
      277,  277,  277,  277,  277,  277,  274,  277,  277,  274,
      274,  277,  277,  277,  277,  274,  277,  277,  277,  277,
      277,  277,  277,  274,  277,  277,  274,  274,  277,  277,
      277,  277,  274,  277,  277,  277,  277,  277,  277,  277,
      274,  277,  277,  277,  277,  277,  277,  277,  277,  277,

      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,    0,  272,  272,  272,  272,  272
    } ;

static yyconst flex_int16_t yy_nxt[1591] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   10,   10,   11,
       12,   13,   14,   15,   15,   16,   15,   17,   15,   15,
       15,   15,   18,   15,   15,   10,   19,   15,   20,   21,
       22,   15,   15,   15,   23,   24,   25,   15,   15,   26,
       15,   15,   27,   28,   29,   15,   15,   15,   15,   15,
       15,   30,   31,   32,   36,   89,   37,   66,   35,   39,
       39,   38,   41,  146,   38,   38,  146,   38,   35,   39,
       39,  109,   41,   35,   35,   35,   88,   42,   43,   35,
       39,   39,   66,   41,   35,   39,   39,   42,   41,   44,
       35,   39,   39,   65,   41,   35,   35,   35,   42,   45,

       35,   39,   39,   42,   41,   33,   35,   39,   39,   42,
       41,   34,   46,   35,   39,   39,   33,   41,   35,   42,
       47,  129,   41,  109,  127,   42,   49,  272,  272,   48,
       50,  272,   42,   51,   35,   39,   39,   35,   41,   35,
       39,   39,   52,   41,  272,   35,   39,   39,  272,   41,
       35,   39,   39,   42,   41,  272,  272,   53,   42,  272,
       35,   35,   35,   55,   42,  272,   54,  272,  272,   42,
       35,   39,   39,   56,   41,   58,  272,  272,   57,   35,
       35,   35,   59,   35,   39,   39,  272,   41,  134,   42,
      272,   35,   39,   39,   60,   41,  272,  272,   36,  272,

       37,  272,   42,   61,  272,   38,  272,   62,   38,   38,
       42,   38,  272,   63,   35,   39,   39,  138,   41,   35,
       39,   39,  272,   41,   35,   39,   39,  272,   41,   35,
       35,   35,   67,   42,   64,   35,   39,   39,   42,   41,
      272,  272,   68,   42,   35,   39,   39,  272,   41,   35,
       39,   39,   69,   41,   42,   35,   39,   39,  272,   41,
       35,   35,   35,   42,  272,  176,   70,  272,   42,   35,
       39,   39,  272,   41,   42,  272,   35,   39,   39,   71,
       41,   35,   39,   39,  114,   41,  272,  272,   42,  272,
       35,   39,   39,   72,   41,   42,  272,   73,  115,  272,

       42,   35,   35,   35,   74,   75,   35,   39,   39,   42,
       41,   35,   39,   39,  272,   41,   35,   39,   39,  272,
       41,  272,   35,   35,   35,   42,   76,   35,   39,   39,
       42,   41,  272,  133,   78,   42,   77,   35,   39,   39,
       79,   41,  150,   35,   39,   39,   42,   41,   35,   39,
       39,  272,   41,   35,   39,   39,   42,   41,   80,   82,
      272,  272,   42,  272,   81,  272,  272,   42,   59,   35,
       39,   39,   42,   41,  272,  272,   83,   35,   39,   39,
      272,   41,   35,   39,   39,  272,   41,  272,   42,   35,
       39,   39,  272,   41,  272,  272,   42,  272,   35,   35,

       35,   42,   84,  272,  272,   35,   39,   39,   42,   41,
       35,   39,   39,   85,   41,   90,   86,   35,   39,   39,
      272,   41,  145,   87,   42,  272,   35,   39,   39,   42,
       41,   35,   35,   35,  272,   68,   42,   35,   39,   39,
      272,   41,   35,   39,   39,   42,   41,   35,   39,   39,
       91,   41,  272,   35,   39,   39,   42,   41,   35,   35,
       35,   42,  151,   35,   39,   39,   94,   41,  272,  272,
       92,  272,   42,  272,  272,   93,  272,   95,  272,   35,
       39,   39,   42,   41,   35,   39,   39,  272,   41,  169,
      272,   35,   39,   39,   96,   41,  272,  272,   42,  272,

       35,   39,   39,   42,   41,   35,   39,   39,   98,   41,
       42,  272,   97,  272,  272,   99,   35,   39,   39,   42,
       41,   35,   39,   39,   42,   41,  272,   35,   39,   39,
      272,   41,  272,  101,  100,   42,   35,   35,   35,  272,
       42,  103,  272,   35,   39,   39,   42,   41,   35,   39,
       39,  272,   41,  272,  102,  104,   35,   39,   39,  272,
       41,  272,   42,  272,  156,  272,  272,   42,   35,   39,
       39,  272,   41,  272,  272,  107,   35,   39,   39,  272,
       41,  105,   35,   39,   39,  272,   41,   42,  106,   35,
       39,   39,  108,   41,  110,   42,   35,   39,   39,  272,

       41,   42,   35,   39,   39,  272,   41,  272,   42,   35,
       39,   39,  272,   41,  272,   42,   35,   39,   39,  111,
       41,   42,  272,  272,  113,   35,   39,   39,   42,   41,
      112,   35,   35,   35,  116,   42,   35,   39,   39,  272,
       41,  272,  117,  272,  119,   35,   39,   39,  272,   41,
      272,  272,  118,  272,  272,   42,   35,   39,   39,  272,
       41,  164,  272,  272,   42,  121,   35,   39,   39,  272,
       41,  272,   35,   39,   39,   42,   41,  272,  120,   35,
       39,   39,  272,   41,  272,   42,   35,   35,   35,  272,
      123,   42,  272,  272,  122,   35,   39,   39,   42,   41,

       35,   39,   39,  272,   41,  272,  172,   35,   39,   39,
      124,   41,  272,  272,   42,  125,   35,   39,   39,   42,
       41,   35,   39,   39,  126,   41,   42,  272,   35,   39,
       39,   68,   41,  272,  272,   42,  272,   35,   39,   39,
       42,   41,  272,  272,  128,  272,  272,   42,  272,   35,
       35,   35,  131,  130,  272,  272,   42,   35,   39,   39,
      272,   41,   35,   39,   39,  272,   41,  272,  272,  132,
       35,   39,   39,  163,   41,  272,   42,  272,   35,   39,
       39,   42,   41,   35,   39,   39,  272,   41,  272,  137,
      272,   35,   35,   35,  136,  135,  272,   42,  272,   35,

       39,   39,   42,   41,   35,   39,   39,  272,   41,  272,
       35,   39,   39,  139,   41,   35,   39,   39,  140,   41,
       35,   35,   35,   42,   35,   39,   39,  158,   41,   42,
      159,   35,   39,   39,   42,   41,  141,  272,  142,  143,
       35,   39,   39,   42,   41,   35,   39,   39,  272,   41,
       42,   35,   39,   39,  180,   41,   35,   35,   35,  147,
      144,   35,   39,   39,   42,   41,  272,  272,  148,  272,
       42,   35,   39,   39,  149,   41,   35,   35,   35,  272,
      152,   35,   39,   39,  272,   41,  184,   35,   35,   35,
      153,  272,   35,   39,   39,  272,   41,   35,   39,   39,

       42,   41,  272,   35,   39,   39,  154,   41,  167,  157,
      155,   42,  272,   35,   39,   39,   42,   41,  272,   35,
       39,   39,   42,   41,  272,  161,  272,   35,   39,   39,
      160,   41,  162,   35,   35,   35,  272,  272,  165,   35,
       35,   35,   35,   35,   35,  272,   42,   35,   35,   35,
      272,  166,   35,   39,   39,  272,   41,  168,   35,   35,
       35,   35,   39,   39,  272,   41,   35,   35,   35,  272,
      170,   42,   35,   39,   39,  171,   41,  272,  173,  272,
       42,  272,  175,   35,   35,   35,   35,   35,   35,  272,
      272,   42,  174,  177,  272,   35,   39,   39,  179,   41,

       35,   35,   35,   35,   35,   35,   35,   35,   35,  272,
      178,   35,   35,   35,   42,  272,  181,  182,   35,   35,
       35,  272,  272,  186,   35,   35,   35,   35,   39,   39,
      272,   41,  272,  185,  272,  190,  272,  183,  272,  187,
       35,   35,   35,  272,  188,  272,   42,   35,   35,   35,
      189,  191,   35,   35,   35,   35,   39,   39,  272,   41,
       35,   39,   39,  272,   41,  272,  272,  194,   35,   35,
       35,   35,   35,   35,   42,  192,   35,   35,   35,   42,
      193,  272,   35,   39,   39,  272,   41,  272,  195,   35,
       35,   35,   35,   35,   35,  272,  272,  196,  272,  272,

      197,   42,   35,   35,   35,   35,   35,   35,   35,   35,
       35,  272,  272,  198,   35,   35,   35,   35,   35,   35,
       35,   39,   39,  272,   41,   35,   35,   35,  201,  272,
      272,  199,   35,   35,   35,   35,   35,   35,  202,  204,
       35,   35,   35,  272,  200,   35,   35,   35,  272,  272,
      203,  206,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,  205,  272,  207,   35,   35,   35,
      208,   35,   35,   35,   35,   35,   35,  272,  210,  272,
      212,   35,   35,   35,   35,   35,   35,   35,   35,   35,
      209,  213,   35,   35,   35,  272,  211,   35,   35,   35,

       35,   35,   35,   35,   35,   35,  272,  272,  216,   35,
       35,   35,  272,  214,  272,  272,  218,  217,  272,  215,
       35,   35,   35,  272,  272,  219,  272,  220,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
      272,  221,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
      272,  272,  223,   35,   35,   35,  225,  272,  272,  222,
       35,   35,   35,  272,  224,   35,   35,   35,   35,   35,
       35,   35,   35,   35,  227,  272,  272,  228,  226,   35,
       35,   35,  272,  272,  229,   35,   35,   35,   35,   35,

       35,  272,  232,  272,  233,  272,  272,  231,  230,   35,
       35,   35,  234,   35,   35,   35,  272,  236,  272,  235,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,  238,  272,  272,  237,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,  272,  272,  242,   35,   35,   35,  239,  272,  241,
      272,   35,   35,   35,  247,  272,  240,  244,   35,   35,
       35,  272,  272,  245,  243,  272,  272,  246,   35,   35,
       35,   35,   35,   35,  272,  272,  249,  248,  250,   35,
       35,   35,   35,   35,   35,   35,   35,   35,  272,  272,

      251,   35,   35,   35,   35,   35,   35,  272,  272,  253,
       35,   35,   35,  272,  252,   35,   35,   35,  272,   35,
       35,   35,   35,   35,   35,  272,  254,   35,   35,   35,
      255,  272,  272,  256,   35,   35,   35,   35,   35,   35,
      272,  272,  257,  258,  272,  272,  259,  260,   35,   35,
       35,   35,   35,   35,  272,  261,  272,  272,  263,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,  272,  264,  272,  262,   35,   35,   35,   35,   35,
       35,   35,   35,   35,  272,   35,   35,   35,  272,  268,
      272,  272,  267,  272,  272,  265,  272,  266,  272,  269,

       35,   35,   35,   35,   35,   35,   35,   35,   35,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  270,  271,   35,   35,   40,   40,   40,   39,   39,
       39,   41,   41,   42,   42,    3,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272
    } ;

static yyconst flex_int16_t yy_chk[1591] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   11,   66,   11,   66,   15,   15,
       15,   11,   15,  146,   11,   11,  129,   11,   16,   16,
       16,   89,   16,   42,   42,   42,   65,   15,   16,   17,
       17,   17,   36,   17,   18,   18,   18,   16,   18,   17,
       19,   19,   19,   34,   19,  107,  107,  107,   17,   18,

       20,   20,   20,   18,   20,   33,   22,   22,   22,   19,
       22,    9,   19,   21,   21,   21,    5,   21,   39,   20,
       19,  109,   39,  109,  107,   22,   20,    3,    0,   19,
       20,    0,   21,   21,   23,   23,   23,   39,   23,   24,
       24,   24,   22,   24,    0,   25,   25,   25,    0,   25,
       26,   26,   26,   23,   26,    0,    0,   23,   24,    0,
      115,  115,  115,   24,   25,    0,   23,    0,    0,   26,
       27,   27,   27,   25,   27,   26,    0,    0,   25,  119,
      119,  119,   26,   28,   28,   28,    0,   28,  115,   27,
        0,   29,   29,   29,   27,   29,    0,    0,   37,    0,

       37,    0,   28,   27,    0,   37,    0,   28,   37,   37,
       29,   37,    0,   29,   40,   40,   40,  119,   40,   43,
       43,   43,    0,   43,   44,   44,   44,    0,   44,  159,
      159,  159,   43,   40,   29,   45,   45,   45,   43,   45,
        0,    0,   44,   44,   46,   46,   46,    0,   46,   47,
       47,   47,   45,   47,   45,   48,   48,   48,    0,   48,
       94,   94,   94,   46,    0,  159,   46,    0,   47,   49,
       49,   49,    0,   49,   48,    0,   50,   50,   50,   47,
       50,   51,   51,   51,   94,   51,    0,    0,   49,    0,
       52,   52,   52,   48,   52,   50,    0,   49,   94,    0,

       51,  114,  114,  114,   50,   51,   53,   53,   53,   52,
       53,   54,   54,   54,    0,   54,   55,   55,   55,    0,
       55,    0,  133,  133,  133,   53,   52,   56,   56,   56,
       54,   56,    0,  114,   54,   55,   53,   57,   57,   57,
       55,   57,  133,   58,   58,   58,   56,   58,   59,   59,
       59,    0,   59,   60,   60,   60,   57,   60,   56,   57,
        0,    0,   58,    0,   56,    0,    0,   59,   58,   61,
       61,   61,   60,   61,    0,    0,   60,   62,   62,   62,
        0,   62,   63,   63,   63,    0,   63,    0,   61,   64,
       64,   64,    0,   64,    0,    0,   62,    0,  127,  127,

      127,   63,   61,    0,    0,   67,   67,   67,   64,   67,
       68,   68,   68,   62,   68,   67,   63,   69,   69,   69,
        0,   69,  127,   64,   67,    0,   70,   70,   70,   68,
       70,  134,  134,  134,    0,   69,   69,   71,   71,   71,
        0,   71,   72,   72,   72,   70,   72,   73,   73,   73,
       70,   73,    0,   74,   74,   74,   71,   74,  152,  152,
      152,   72,  134,   75,   75,   75,   73,   75,    0,    0,
       71,    0,   74,    0,    0,   72,    0,   74,    0,   76,
       76,   76,   75,   76,   77,   77,   77,    0,   77,  152,
        0,   78,   78,   78,   75,   78,    0,    0,   76,    0,

       79,   79,   79,   77,   79,   80,   80,   80,   77,   80,
       78,    0,   76,    0,    0,   78,   81,   81,   81,   79,
       81,   82,   82,   82,   80,   82,    0,   83,   83,   83,
        0,   83,    0,   80,   79,   81,  138,  138,  138,    0,
       82,   82,    0,   84,   84,   84,   83,   84,   85,   85,
       85,    0,   85,    0,   81,   83,   86,   86,   86,    0,
       86,    0,   84,    0,  138,    0,    0,   85,   87,   87,
       87,    0,   87,    0,    0,   86,   90,   90,   90,    0,
       90,   84,   91,   91,   91,    0,   91,   87,   85,   92,
       92,   92,   87,   92,   90,   90,   93,   93,   93,    0,

       93,   91,   95,   95,   95,    0,   95,    0,   92,   96,
       96,   96,    0,   96,    0,   93,   97,   97,   97,   91,
       97,   95,    0,    0,   93,   98,   98,   98,   96,   98,
       92,  147,  147,  147,   95,   97,   99,   99,   99,    0,
       99,    0,   96,    0,   98,  100,  100,  100,    0,  100,
        0,    0,   97,    0,    0,   99,  101,  101,  101,    0,
      101,  147,    0,    0,  100,  100,  102,  102,  102,    0,
      102,    0,  103,  103,  103,  101,  103,    0,   99,  104,
      104,  104,    0,  104,    0,  102,  155,  155,  155,    0,
      102,  103,    0,    0,  101,  105,  105,  105,  104,  105,

      106,  106,  106,    0,  106,    0,  155,  108,  108,  108,
      103,  108,    0,    0,  105,  104,  111,  111,  111,  106,
      111,  110,  110,  110,  106,  110,  108,    0,  112,  112,
      112,  110,  112,    0,    0,  111,    0,  113,  113,  113,
      110,  113,    0,    0,  108,    0,    0,  112,    0,  145,
      145,  145,  112,  111,    0,    0,  113,  116,  116,  116,
        0,  116,  117,  117,  117,    0,  117,    0,    0,  113,
      118,  118,  118,  145,  118,    0,  116,    0,  120,  120,
      120,  117,  120,  121,  121,  121,    0,  121,    0,  118,
        0,  140,  140,  140,  117,  116,    0,  120,    0,  122,

      122,  122,  121,  122,  123,  123,  123,    0,  123,    0,
      124,  124,  124,  121,  124,  125,  125,  125,  122,  125,
      163,  163,  163,  123,  126,  126,  126,  140,  126,  124,
      140,  128,  128,  128,  125,  128,  123,    0,  124,  125,
      130,  130,  130,  126,  130,  131,  131,  131,    0,  131,
      128,  132,  132,  132,  163,  132,  167,  167,  167,  130,
      126,  135,  135,  135,  131,  135,    0,    0,  131,    0,
      132,  136,  136,  136,  132,  136,  137,  137,  137,    0,
      135,  139,  139,  139,    0,  139,  167,  150,  150,  150,
      136,    0,  141,  141,  141,    0,  141,  142,  142,  142,

      139,  142,    0,  143,  143,  143,  137,  143,  150,  139,
      137,  141,    0,  144,  144,  144,  142,  144,    0,  148,
      148,  148,  143,  148,    0,  143,    0,  149,  149,  149,
      142,  149,  144,  151,  151,  151,    0,    0,  148,  153,
      153,  153,  154,  154,  154,    0,  149,  156,  156,  156,
        0,  149,  157,  157,  157,    0,  157,  151,  158,  158,
      158,  160,  160,  160,    0,  160,  162,  162,  162,    0,
      153,  157,  161,  161,  161,  154,  161,    0,  156,    0,
      160,    0,  158,  164,  164,  164,  165,  165,  165,    0,
        0,  161,  157,  160,    0,  166,  166,  166,  162,  166,

      168,  168,  168,  169,  169,  169,  170,  170,  170,    0,
      161,  173,  173,  173,  166,    0,  164,  165,  171,  171,
      171,    0,    0,  169,  172,  172,  172,  174,  174,  174,
        0,  174,    0,  168,    0,  173,    0,  166,    0,  170,
      175,  175,  175,    0,  171,    0,  174,  179,  179,  179,
      172,  174,  176,  176,  176,  177,  177,  177,    0,  177,
      178,  178,  178,    0,  178,    0,    0,  179,  180,  180,
      180,  181,  181,  181,  177,  175,  182,  182,  182,  178,
      176,    0,  183,  183,  183,    0,  183,    0,  180,  184,
      184,  184,  185,  185,  185,    0,    0,  181,    0,    0,

      182,  183,  186,  186,  186,  187,  187,  187,  188,  188,
      188,    0,    0,  184,  189,  189,  189,  190,  190,  190,
      191,  191,  191,    0,  191,  192,  192,  192,  187,    0,
        0,  185,  193,  193,  193,  194,  194,  194,  189,  191,
      195,  195,  195,    0,  186,  196,  196,  196,    0,    0,
      190,  193,  197,  197,  197,  198,  198,  198,  199,  199,
      199,  200,  200,  200,  192,    0,  194,  201,  201,  201,
      195,  202,  202,  202,  203,  203,  203,    0,  198,    0,
      200,  204,  204,  204,  205,  205,  205,  206,  206,  206,
      197,  201,  207,  207,  207,    0,  199,  208,  208,  208,

      209,  209,  209,  210,  210,  210,    0,    0,  205,  211,
      211,  211,    0,  203,    0,    0,  207,  206,    0,  204,
      212,  212,  212,    0,    0,  208,    0,  209,  213,  213,
      213,  214,  214,  214,  215,  215,  215,  216,  216,  216,
        0,  212,  217,  217,  217,  218,  218,  218,  219,  219,
      219,  220,  220,  220,  221,  221,  221,  222,  222,  222,
        0,    0,  215,  223,  223,  223,  217,    0,    0,  214,
      224,  224,  224,    0,  216,  225,  225,  225,  226,  226,
      226,  227,  227,  227,  220,    0,    0,  221,  219,  228,
      228,  228,    0,    0,  223,  229,  229,  229,  230,  230,

      230,    0,  226,    0,  227,    0,    0,  225,  224,  231,
      231,  231,  228,  232,  232,  232,    0,  230,    0,  229,
      233,  233,  233,  234,  234,  234,  235,  235,  235,  236,
      236,  236,  232,    0,    0,  231,  237,  237,  237,  238,
      238,  238,  239,  239,  239,  240,  240,  240,  241,  241,
      241,    0,    0,  236,  242,  242,  242,  233,    0,  235,
        0,  243,  243,  243,  240,    0,  234,  238,  244,  244,
      244,    0,    0,  238,  237,    0,    0,  238,  245,  245,
      245,  246,  246,  246,    0,    0,  242,  241,  243,  247,
      247,  247,  248,  248,  248,  249,  249,  249,    0,    0,

      244,  250,  250,  250,  251,  251,  251,    0,    0,  246,
      252,  252,  252,    0,  245,  253,  253,  253,    0,  254,
      254,  254,  255,  255,  255,    0,  247,  256,  256,  256,
      248,    0,    0,  249,  257,  257,  257,  258,  258,  258,
        0,    0,  251,  252,    0,    0,  253,  254,  259,  259,
      259,  260,  260,  260,    0,  256,    0,    0,  258,  261,
      261,  261,  262,  262,  262,  263,  263,  263,  264,  264,
      264,    0,  259,    0,  257,  265,  265,  265,  266,  266,
      266,  267,  267,  267,    0,  268,  268,  268,    0,  263,
        0,    0,  262,    0,    0,  260,    0,  261,    0,  265,

      269,  269,  269,  270,  270,  270,  271,  271,  271,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  266,  268,  273,  273,  274,  274,  274,  275,  275,
      275,  276,  276,  277,  277,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/config_parser/lexer.l"
#line 2 "src/config_parser/lexer.l"
	#include <stdio.h>
	//DELETE THIS SHIT ON MAC
	//IM SERIOUS
	typedef struct Config Config;
	#include "ConfigParser.hpp"
	int yylex(void);
#define YY_NO_INPUT 1
#line 896 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 13 "src/config_parser/lexer.l"


#line 1079 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 273 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1536 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 15 "src/config_parser/lexer.l"
return ACCLOG;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 16 "src/config_parser/lexer.l"
return ALLOWED_METHODS;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 17 "src/config_parser/lexer.l"
return AUTOINDEX;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 18 "src/config_parser/lexer.l"
return CGI_ENABLED;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 19 "src/config_parser/lexer.l"
return CGI_TIMEOUT;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 20 "src/config_parser/lexer.l"
return CLIENT_MAX_BODY_SIZE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 21 "src/config_parser/lexer.l"
return DAEMON;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 22 "src/config_parser/lexer.l"
return ERRLOG;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 23 "src/config_parser/lexer.l"
return ERROR_PAGE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 24 "src/config_parser/lexer.l"
return IDLE_TIMEOUT;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 25 "src/config_parser/lexer.l"
return INDEX;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 26 "src/config_parser/lexer.l"
return KA_TIMEOUT;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 27 "src/config_parser/lexer.l"
return REQUEST_LENGTH;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 28 "src/config_parser/lexer.l"
return URI_LENGTH;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 29 "src/config_parser/lexer.l"
return LISTEN;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 30 "src/config_parser/lexer.l"
return LOCATION;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 31 "src/config_parser/lexer.l"
return REDIRECTION; 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 32 "src/config_parser/lexer.l"
return ROOT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 33 "src/config_parser/lexer.l"
return SERVER;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 34 "src/config_parser/lexer.l"
return SERVER_NAME;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 35 "src/config_parser/lexer.l"
return KA_TIME;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 36 "src/config_parser/lexer.l"
return KA_PROBES;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 37 "src/config_parser/lexer.l"
return KA_INTERVAL;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 38 "src/config_parser/lexer.l"
return MIMETYPES;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 39 "src/config_parser/lexer.l"
return URI;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 40 "src/config_parser/lexer.l"
;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 41 "src/config_parser/lexer.l"
return QUOTE;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 42 "src/config_parser/lexer.l"
return OBRACE;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 43 "src/config_parser/lexer.l"
return EBRACE;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 44 "src/config_parser/lexer.l"
return SEMICOLON;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 45 "src/config_parser/lexer.l"
return COLON;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 46 "src/config_parser/lexer.l"
return EQUALS;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 47 "src/config_parser/lexer.l"
return TILDE;
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 48 "src/config_parser/lexer.l"
/* пропускаем концы строк */;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 49 "src/config_parser/lexer.l"
/* пропускаем пробелы */;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 50 "src/config_parser/lexer.l"
{ yylval.number=!strcmp(yytext,"on"); return STATE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 51 "src/config_parser/lexer.l"
{ yylval.string=strdup(yytext); return HTTP_METHOD; }	
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 52 "src/config_parser/lexer.l"
{ yylval.string=strdup(yytext);	return FILESIZE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 53 "src/config_parser/lexer.l"
{ yylval.string=strdup(yytext); return IP; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 54 "src/config_parser/lexer.l"
{ yylval.number=atoi(yytext); 	return NUMBER; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 55 "src/config_parser/lexer.l"
{ yylval.string=strdup(yytext); return WORD; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 56 "src/config_parser/lexer.l"
{ yylval.string=strdup(yytext); return PATH; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 57 "src/config_parser/lexer.l"
{ yylval.string=strdup(yytext); return URL; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 58 "src/config_parser/lexer.l"
ECHO;
	YY_BREAK
#line 1383 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 273 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 273 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 272);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 58 "src/config_parser/lexer.l"



