
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 43
#define YY_END_OF_BUFFER 44
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[276] =
    {   0,
        0,    0,   44,   43,   34,   33,   26,   43,   41,   39,
       30,   29,   31,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   27,   28,
       32,   34,    0,   41,   41,   39,   37,   41,   40,   42,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   35,   40,   40,
       40,   40,   40,    0,   41,   40,   36,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   25,   41,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,

       40,   40,   40,   18,   40,   40,   40,   41,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   11,   40,
       40,   40,   40,   40,   40,   40,   24,   41,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   15,
       40,   40,   19,   40,   38,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   16,   17,   40,   40,   40,
       40,    3,   40,   40,   40,   40,    8,   40,   40,   40,
       40,   40,   40,   40,    1,   40,   40,   40,   40,   40,

        9,   40,   40,   40,   40,   40,   40,   40,   40,    5,
       40,    7,   40,   40,   40,   40,   20,   40,   40,   40,
       40,   10,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
        2,    4,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   14,   40,   40,   40,   40,   12,   40,   40,
       40,   40,   40,   40,   40,   40,   21,   40,   40,   23,
       40,    6,   13,   22,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    6,    7,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   10,   11,    1,
       12,    1,    1,    1,   13,   14,   13,   15,   16,   13,
       17,   13,   13,   13,   18,   19,   20,   13,   21,   22,
       13,   13,   23,   24,   13,   13,   13,   13,   13,   13,
        1,    1,    1,    1,   25,    1,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   13,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   51,    1,   52,   53,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[54] =
    {   0,
        1,    1,    1,    1,    1,    2,    3,    3,    3,    4,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    2,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[281] =
    {   0,
        0,    0,  113, 1559,  105, 1559, 1559,   57,    0,   47,
     1559, 1559, 1559,   52,   62,   73,   78,   98,   84,  104,
      111,  125,  131,  139,  152,  159,  185,  193, 1559, 1559,
     1559,   99,   55,    0,   73,  199,    0,   90,  216,    0,
       67,  221,  226,  237,  246,  251,  257,  271,  278,  283,
      292,  308,  313,  318,  329,  339,  345,  350,  355,  371,
      379,  384,  391,   42,   48,  407,  412,  419,  428,  439,
      444,  449,  455,  465,  481,  486,  493,  502,  507,  518,
      523,  529,  545,  550,  558,  570, 1559,   62,  578,  584,
      591,  598,  168,  604,  611,  618,  627,  638,  647,  658,

      668,  674,  681,  697,  702,  174,  709,   86,  723,  718,
      730,  739,  231,  180,  759,  764,  772,  324,  780,  785,
      801,  806,  812,  817,  826,  164,  833,   57,  842,  847,
      853,  433,  303,  863,  873,  878,  399,  883,  793,  894,
      899,  905,  915,  539,   54,  633,  921,  929,  751,  935,
      460,  858,  941,  688,  944,  950,  955,  565,  961,  966,
      971,  822,  976,  981,  987,  994,  998, 1013, 1016, 1019,
     1022, 1026, 1034, 1039, 1042, 1059, 1064, 1055, 1071, 1079,
     1084, 1088, 1093, 1096, 1099, 1102, 1109, 1112, 1115, 1118,
     1128, 1131, 1138, 1142, 1145, 1151, 1154, 1157, 1160, 1163,

     1173, 1176, 1180, 1183, 1191, 1196, 1199, 1202, 1208, 1211,
     1222, 1233, 1236, 1239, 1244, 1247, 1250, 1253, 1256, 1259,
     1262, 1268, 1275, 1278, 1282, 1285, 1290, 1298, 1301, 1310,
     1317, 1325, 1328, 1331, 1337, 1340, 1343, 1348, 1352, 1357,
     1360, 1363, 1369, 1377, 1380, 1392, 1396, 1399, 1402, 1405,
     1408, 1413, 1420, 1423, 1431, 1436, 1443, 1439, 1447, 1452,
     1455, 1458, 1468, 1472, 1477, 1484, 1487, 1493, 1496, 1499,
     1503, 1513, 1518, 1521, 1559, 1545, 1547, 1550, 1552, 1555
    } ;

static yyconst flex_int16_t yy_def[281] =
    {   0,
      275,    1,  275,  275,  275,  275,  275,  275,  276,  276,
      275,  275,  275,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  275,  275,
      275,  275,  275,  276,  276,  276,  276,  278,  277,  279,
      280,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  275,  276,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  275,  276,  277,  277,
      277,  277,  280,  277,  277,  277,  277,  277,  277,  277,

      277,  277,  277,  277,  277,  280,  277,  276,  277,  277,
      277,  277,  280,  280,  277,  277,  277,  280,  277,  277,
      277,  277,  277,  277,  277,  280,  277,  276,  277,  277,
      277,  280,  280,  277,  277,  280,  280,  277,  280,  277,
      277,  277,  277,  280,  276,  280,  277,  277,  280,  280,
      280,  280,  280,  280,  280,  277,  280,  280,  277,  277,
      280,  280,  280,  280,  277,  280,  280,  280,  280,  280,
      280,  280,  277,  280,  280,  277,  277,  280,  280,  280,
      280,  277,  280,  280,  280,  280,  280,  280,  280,  277,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,

      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,    0,  275,  275,  275,  275,  275
    } ;

static yyconst flex_int16_t yy_nxt[1613] =
    {   0,
        4,    5,    6,    7,    8,    9,    9,    9,   10,   11,
       12,   13,   14,   14,   15,   14,   16,   14,   14,   14,
       14,   17,   14,   14,    9,   18,   14,   19,   20,   21,
       14,   14,   14,   22,   23,   24,   14,   14,   25,   14,
       14,   26,   27,   28,   14,   14,   14,   14,   14,   14,
       29,   30,   31,   35,   88,   36,   65,   34,   38,   38,
       37,   40,  145,   37,   37,  145,   37,   34,   38,   38,
      108,   40,   34,   34,   34,   87,   41,   42,   34,   38,
       38,   65,   40,   34,   38,   38,   41,   40,   43,   34,
       38,   38,  128,   40,  108,   34,   64,   41,   44,   40,

       32,   33,   41,   34,   38,   38,   32,   40,   41,   34,
       38,   38,  275,   40,   34,   48,   34,   38,   38,   49,
       40,  275,   41,  275,  275,   45,  275,  275,   41,   50,
       34,   38,   38,   46,   40,   41,   34,   38,   38,  275,
       40,  275,   47,  275,   34,   38,   38,  275,   40,   41,
      275,  275,   51,   52,  275,   41,  275,   34,   38,   38,
       54,   40,   53,   41,   34,   38,   38,  275,   40,   34,
       34,   34,   55,   34,   34,   34,   41,   56,  275,   34,
       34,   34,   57,   41,  275,   34,   34,   34,   59,   58,
       34,   38,   38,  144,   40,  275,  275,   60,   34,   38,

       38,  113,   40,  275,  275,   35,  275,   36,  126,   41,
      275,  114,   37,  133,   61,   37,   37,   41,   37,  275,
       62,   34,   38,   38,  275,   40,   34,   38,   38,  275,
       40,   34,   38,   38,  275,   40,   34,   34,   34,   66,
       41,   63,   34,   38,   38,   41,   40,  275,  275,   67,
       41,   34,   38,   38,  275,   40,   34,   38,   38,   68,
       40,   41,   34,   38,   38,  275,   40,  275,  132,  275,
       41,  275,  275,   69,  275,   41,   34,   38,   38,  275,
       40,   41,  275,   34,   38,   38,   70,   40,   34,   38,
       38,  275,   40,  275,  275,   41,  275,   34,   38,   38,

       71,   40,   41,  275,   72,  275,  275,   41,   34,   34,
       34,   73,   74,   34,   38,   38,   41,   40,   34,   38,
       38,  275,   40,   34,   38,   38,  275,   40,  275,   34,
       34,   34,   41,   75,   34,   38,   38,   41,   40,  150,
      275,   77,   41,   76,   34,   38,   38,   78,   40,  275,
       34,   38,   38,   41,   40,   34,   38,   38,  275,   40,
       34,   38,   38,   41,   40,   79,   81,  137,  275,   41,
      275,   80,  275,  275,   41,   58,   34,   38,   38,   41,
       40,  275,  275,   82,   34,   38,   38,  275,   40,   34,
       38,   38,  275,   40,  275,   41,   34,   38,   38,  275,

       40,  275,  275,   41,   34,   34,   34,  275,   41,   83,
      275,  275,   34,   38,   38,   41,   40,   34,   38,   38,
       84,   40,   89,   85,   34,   38,   38,  275,   40,  275,
       86,   41,  155,   34,   38,   38,   41,   40,   34,   34,
       34,  275,   67,   41,   34,   38,   38,  275,   40,   34,
       38,   38,   41,   40,   34,   38,   38,   90,   40,  275,
       34,   38,   38,   41,   40,   34,   34,   34,   41,  275,
       34,   38,   38,   93,   40,  275,  149,   91,  275,   41,
      275,  275,   92,  275,   94,  275,   34,   38,   38,   41,
       40,   34,   38,   38,  275,   40,  168,  275,   34,   38,

       38,   95,   40,  275,  275,   41,  275,   34,   38,   38,
       41,   40,   34,   38,   38,   97,   40,   41,  275,   96,
      275,  275,   98,   34,   38,   38,   41,   40,   34,   38,
       38,   41,   40,  275,   34,   38,   38,  275,   40,  275,
      100,   99,   41,  275,   34,   34,   34,   41,  102,  275,
       34,   38,   38,   41,   40,   34,   38,   38,  275,   40,
      275,  101,  103,   34,   38,   38,  275,   40,  162,   41,
       34,   34,   34,  275,   41,   34,   38,   38,  275,   40,
      275,  275,  106,   34,   38,   38,  275,   40,  104,   34,
       38,   38,  275,   40,   41,  105,   34,   38,   38,  107,

       40,  109,   41,   34,   38,   38,  175,   40,   41,   34,
       38,   38,  275,   40,  275,   41,   34,   38,   38,  275,
       40,  275,   41,   34,   38,   38,  110,   40,   41,  275,
      275,  112,   34,   38,   38,   41,   40,  111,   34,   34,
       34,  115,   41,   34,   38,   38,  275,   40,  275,  116,
      275,  118,   34,   38,   38,  275,   40,  275,  275,  117,
      275,  275,   41,   34,   38,   38,  275,   40,  163,  275,
      275,   41,  120,   34,   38,   38,  275,   40,  275,   34,
       38,   38,   41,   40,  275,  119,   34,   38,   38,  275,
       40,  275,   41,   34,   34,   34,  275,  122,   41,  275,

      275,  121,   34,   38,   38,   41,   40,   34,   38,   38,
      275,   40,  275,  171,   34,   38,   38,  123,   40,  275,
      275,   41,  124,   34,   38,   38,   41,   40,   34,   38,
       38,  125,   40,   41,  275,   34,   38,   38,   67,   40,
      275,  275,   41,  275,   34,   38,   38,   41,   40,  275,
      275,  127,  275,  275,   41,  275,   34,   34,   34,  130,
      129,  275,  275,   41,   34,   38,   38,  275,   40,   34,
       38,   38,  275,   40,  275,  275,  131,   34,   38,   38,
      166,   40,  275,   41,  275,   34,   38,   38,   41,   40,
       34,   38,   38,  275,   40,  275,  136,  275,   34,   34,

       34,  135,  134,  275,   41,  275,   34,   38,   38,   41,
       40,   34,   38,   38,  275,   40,  275,   34,   38,   38,
      138,   40,   34,   38,   38,  139,   40,   34,   34,   34,
       41,   34,   38,   38,  157,   40,   41,  158,   34,   38,
       38,   41,   40,  140,  275,  141,  142,   34,   38,   38,
       41,   40,   34,   38,   38,  275,   40,   41,   34,   38,
       38,  179,   40,   34,   34,   34,  146,  143,   34,   38,
       38,   41,   40,  275,  275,  147,  275,   41,   34,   38,
       38,  148,   40,   34,   34,   34,  275,  151,   34,   38,
       38,  275,   40,  275,  169,  275,  275,  152,  275,   34,

       38,   38,  275,   40,   34,   38,   38,   41,   40,  275,
       34,   38,   38,  153,   40,  275,  156,  154,   41,  275,
       34,   38,   38,   41,   40,  275,   34,   38,   38,   41,
       40,  275,  160,  275,   34,   38,   38,  159,   40,  161,
       34,   34,   34,  275,  275,  164,   34,   34,   34,   34,
       34,   34,  275,   41,  275,   34,   38,   38,  165,   40,
       34,   34,   34,  275,  167,  275,   34,   38,   38,  275,
       40,   34,   38,   38,   41,   40,   34,   34,   34,  170,
      172,   34,   34,   34,  174,   41,   34,   34,   34,  275,
       41,  275,   34,   38,   38,  173,   40,  275,  176,   34,

       34,   34,  275,   34,   34,   34,  275,  275,  178,  177,
      275,   41,  275,  275,  180,  275,  275,  181,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
      275,   34,   34,   34,  182,  183,  184,  275,  185,   34,
       38,   38,  275,   40,   34,   34,   34,   34,   34,   34,
      187,  275,  275,  188,  186,  189,  275,  275,   41,  275,
       34,   34,   34,  190,   34,   38,   38,  275,   40,   34,
       38,   38,  275,   40,  275,  192,   34,   34,   34,  191,
      193,  275,  275,   41,   34,   34,   34,  275,   41,   34,
       34,   34,  275,   34,   38,   38,  194,   40,   34,   34,

       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
      195,  275,   41,  196,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   38,   38,  275,   40,  275,  275,
      200,  275,  197,   34,   34,   34,   34,   34,   34,  275,
      198,  201,  203,   34,   34,   34,  199,   34,   34,   34,
       34,   34,   34,  202,  275,  205,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,  275,  204,  275,  206,  275,  275,  207,   34,   34,
       34,   34,   34,   34,  211,   34,   34,   34,   34,   34,
       34,  275,  212,  275,  208,  209,   34,   34,   34,  275,

      210,   34,   34,   34,   34,   34,   34,   34,   34,   34,
      275,  275,  215,   34,   34,   34,   34,   34,   34,  275,
      213,  275,  275,  214,  275,  217,  216,   34,   34,   34,
      275,  275,  218,  275,  219,  275,  275,  220,   34,   34,
       34,   34,   34,   34,   34,   34,   34,  275,  221,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
      275,  275,  223,   34,   34,   34,  225,  275,  275,  222,
       34,   34,   34,   34,   34,   34,  224,   34,   34,   34,
       34,   34,   34,  275,  227,   34,   34,   34,  226,  275,

      229,  275,  228,   34,   34,   34,   34,   34,   34,  275,
      275,  230,  275,  275,  233,   34,   34,   34,  234,  232,
      275,  231,   34,   34,   34,  275,  275,  235,  275,  236,
       34,   34,   34,   34,   34,   34,   34,   34,   34,  237,
      275,  238,   34,   34,   34,   34,   34,   34,   34,   34,
       34,  275,  240,   34,   34,   34,  239,   34,   34,   34,
      275,  275,   34,   34,   34,   34,   34,   34,   34,   34,
       34,  275,  275,  241,   34,   34,   34,  245,  242,  275,
      275,  244,   34,   34,   34,   34,   34,   34,  243,  275,
      247,  275,  275,  250,  275,  246,  248,   34,   34,   34,

      249,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,  275,  252,   34,   34,
       34,  251,  275,  275,  253,   34,   34,   34,   34,   34,
       34,  275,  275,  254,  275,  256,   34,   34,   34,  275,
      255,   34,   34,   34,   34,   34,   34,  257,   34,   34,
       34,  258,   34,   34,   34,  275,  259,   34,   34,   34,
       34,   34,   34,   34,   34,   34,  260,  275,  275,  261,
      275,  275,  262,   34,   34,   34,  263,   34,   34,   34,
      264,  266,   34,   34,   34,  275,  275,  267,  275,   34,
       34,   34,   34,   34,   34,  275,  275,  265,   34,   34,

       34,   34,   34,   34,   34,   34,   34,  275,   34,   34,
       34,  275,  270,  271,  275,  269,  275,  268,   34,   34,
       34,  275,  272,   34,   34,   34,   34,   34,   34,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  273,  274,   34,   34,   39,   39,
       39,   38,   38,   38,   40,   40,   41,   41,    3,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,

      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275
    } ;

static yyconst flex_int16_t yy_chk[1613] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   10,   65,   10,   65,   14,   14,   14,
       10,   14,  145,   10,   10,  128,   10,   15,   15,   15,
       88,   15,   41,   41,   41,   64,   14,   15,   16,   16,
       16,   35,   16,   17,   17,   17,   15,   17,   16,   19,
       19,   19,  108,   19,  108,   38,   33,   16,   17,   38,

       32,    8,   17,   18,   18,   18,    5,   18,   19,   20,
       20,   20,    3,   20,   38,   19,   21,   21,   21,   19,
       21,    0,   18,    0,    0,   18,    0,    0,   20,   20,
       22,   22,   22,   18,   22,   21,   23,   23,   23,    0,
       23,    0,   18,    0,   24,   24,   24,    0,   24,   22,
        0,    0,   21,   22,    0,   23,    0,   25,   25,   25,
       23,   25,   22,   24,   26,   26,   26,    0,   26,  126,
      126,  126,   24,   93,   93,   93,   25,   24,    0,  106,
      106,  106,   25,   26,    0,  114,  114,  114,   26,   25,
       27,   27,   27,  126,   27,    0,    0,   26,   28,   28,

       28,   93,   28,    0,    0,   36,    0,   36,  106,   27,
        0,   93,   36,  114,   27,   36,   36,   28,   36,    0,
       28,   39,   39,   39,    0,   39,   42,   42,   42,    0,
       42,   43,   43,   43,    0,   43,  113,  113,  113,   42,
       39,   28,   44,   44,   44,   42,   44,    0,    0,   43,
       43,   45,   45,   45,    0,   45,   46,   46,   46,   44,
       46,   44,   47,   47,   47,    0,   47,    0,  113,    0,
       45,    0,    0,   45,    0,   46,   48,   48,   48,    0,
       48,   47,    0,   49,   49,   49,   46,   49,   50,   50,
       50,    0,   50,    0,    0,   48,    0,   51,   51,   51,

       47,   51,   49,    0,   48,    0,    0,   50,  133,  133,
      133,   49,   50,   52,   52,   52,   51,   52,   53,   53,
       53,    0,   53,   54,   54,   54,    0,   54,    0,  118,
      118,  118,   52,   51,   55,   55,   55,   53,   55,  133,
        0,   53,   54,   52,   56,   56,   56,   54,   56,    0,
       57,   57,   57,   55,   57,   58,   58,   58,    0,   58,
       59,   59,   59,   56,   59,   55,   56,  118,    0,   57,
        0,   55,    0,    0,   58,   57,   60,   60,   60,   59,
       60,    0,    0,   59,   61,   61,   61,    0,   61,   62,
       62,   62,    0,   62,    0,   60,   63,   63,   63,    0,

       63,    0,    0,   61,  137,  137,  137,    0,   62,   60,
        0,    0,   66,   66,   66,   63,   66,   67,   67,   67,
       61,   67,   66,   62,   68,   68,   68,    0,   68,    0,
       63,   66,  137,   69,   69,   69,   67,   69,  132,  132,
      132,    0,   68,   68,   70,   70,   70,    0,   70,   71,
       71,   71,   69,   71,   72,   72,   72,   69,   72,    0,
       73,   73,   73,   70,   73,  151,  151,  151,   71,    0,
       74,   74,   74,   72,   74,    0,  132,   70,    0,   73,
        0,    0,   71,    0,   73,    0,   75,   75,   75,   74,
       75,   76,   76,   76,    0,   76,  151,    0,   77,   77,

       77,   74,   77,    0,    0,   75,    0,   78,   78,   78,
       76,   78,   79,   79,   79,   76,   79,   77,    0,   75,
        0,    0,   77,   80,   80,   80,   78,   80,   81,   81,
       81,   79,   81,    0,   82,   82,   82,    0,   82,    0,
       79,   78,   80,    0,  144,  144,  144,   81,   81,    0,
       83,   83,   83,   82,   83,   84,   84,   84,    0,   84,
        0,   80,   82,   85,   85,   85,    0,   85,  144,   83,
      158,  158,  158,    0,   84,   86,   86,   86,    0,   86,
        0,    0,   85,   89,   89,   89,    0,   89,   83,   90,
       90,   90,    0,   90,   86,   84,   91,   91,   91,   86,

       91,   89,   89,   92,   92,   92,  158,   92,   90,   94,
       94,   94,    0,   94,    0,   91,   95,   95,   95,    0,
       95,    0,   92,   96,   96,   96,   90,   96,   94,    0,
        0,   92,   97,   97,   97,   95,   97,   91,  146,  146,
      146,   94,   96,   98,   98,   98,    0,   98,    0,   95,
        0,   97,   99,   99,   99,    0,   99,    0,    0,   96,
        0,    0,   98,  100,  100,  100,    0,  100,  146,    0,
        0,   99,   99,  101,  101,  101,    0,  101,    0,  102,
      102,  102,  100,  102,    0,   98,  103,  103,  103,    0,
      103,    0,  101,  154,  154,  154,    0,  101,  102,    0,

        0,  100,  104,  104,  104,  103,  104,  105,  105,  105,
        0,  105,    0,  154,  107,  107,  107,  102,  107,    0,
        0,  104,  103,  110,  110,  110,  105,  110,  109,  109,
      109,  105,  109,  107,    0,  111,  111,  111,  109,  111,
        0,    0,  110,    0,  112,  112,  112,  109,  112,    0,
        0,  107,    0,    0,  111,    0,  149,  149,  149,  111,
      110,    0,    0,  112,  115,  115,  115,    0,  115,  116,
      116,  116,    0,  116,    0,    0,  112,  117,  117,  117,
      149,  117,    0,  115,    0,  119,  119,  119,  116,  119,
      120,  120,  120,    0,  120,    0,  117,    0,  139,  139,

      139,  116,  115,    0,  119,    0,  121,  121,  121,  120,
      121,  122,  122,  122,    0,  122,    0,  123,  123,  123,
      120,  123,  124,  124,  124,  121,  124,  162,  162,  162,
      122,  125,  125,  125,  139,  125,  123,  139,  127,  127,
      127,  124,  127,  122,    0,  123,  124,  129,  129,  129,
      125,  129,  130,  130,  130,    0,  130,  127,  131,  131,
      131,  162,  131,  152,  152,  152,  129,  125,  134,  134,
      134,  130,  134,    0,    0,  130,    0,  131,  135,  135,
      135,  131,  135,  136,  136,  136,    0,  134,  138,  138,
      138,    0,  138,    0,  152,    0,    0,  135,    0,  140,

      140,  140,    0,  140,  141,  141,  141,  138,  141,    0,
      142,  142,  142,  136,  142,    0,  138,  136,  140,    0,
      143,  143,  143,  141,  143,    0,  147,  147,  147,  142,
      147,    0,  142,    0,  148,  148,  148,  141,  148,  143,
      150,  150,  150,    0,    0,  147,  153,  153,  153,  155,
      155,  155,    0,  148,    0,  156,  156,  156,  148,  156,
      157,  157,  157,    0,  150,    0,  159,  159,  159,    0,
      159,  160,  160,  160,  156,  160,  161,  161,  161,  153,
      155,  163,  163,  163,  157,  159,  164,  164,  164,    0,
      160,    0,  165,  165,  165,  156,  165,    0,  159,  166,

      166,  166,    0,  167,  167,  167,    0,    0,  161,  160,
        0,  165,    0,    0,  163,    0,    0,  164,  168,  168,
      168,  169,  169,  169,  170,  170,  170,  171,  171,  171,
        0,  172,  172,  172,  165,  166,  167,    0,  168,  173,
      173,  173,    0,  173,  174,  174,  174,  175,  175,  175,
      170,    0,    0,  171,  169,  172,    0,    0,  173,    0,
      178,  178,  178,  173,  176,  176,  176,    0,  176,  177,
      177,  177,    0,  177,    0,  175,  179,  179,  179,  174,
      178,    0,    0,  176,  180,  180,  180,    0,  177,  181,
      181,  181,    0,  182,  182,  182,  179,  182,  183,  183,

      183,  184,  184,  184,  185,  185,  185,  186,  186,  186,
      180,    0,  182,  181,  187,  187,  187,  188,  188,  188,
      189,  189,  189,  190,  190,  190,    0,  190,    0,    0,
      186,    0,  183,  191,  191,  191,  192,  192,  192,    0,
      184,  188,  190,  193,  193,  193,  185,  194,  194,  194,
      195,  195,  195,  189,    0,  192,  196,  196,  196,  197,
      197,  197,  198,  198,  198,  199,  199,  199,  200,  200,
      200,    0,  191,    0,  193,    0,    0,  194,  201,  201,
      201,  202,  202,  202,  199,  203,  203,  203,  204,  204,
      204,    0,  200,    0,  196,  197,  205,  205,  205,    0,

      198,  206,  206,  206,  207,  207,  207,  208,  208,  208,
        0,    0,  204,  209,  209,  209,  210,  210,  210,    0,
      202,    0,    0,  203,    0,  206,  205,  211,  211,  211,
        0,    0,  207,    0,  208,    0,    0,  209,  212,  212,
      212,  213,  213,  213,  214,  214,  214,    0,  211,  215,
      215,  215,  216,  216,  216,  217,  217,  217,  218,  218,
      218,  219,  219,  219,  220,  220,  220,  221,  221,  221,
        0,    0,  214,  222,  222,  222,  216,    0,    0,  213,
      223,  223,  223,  224,  224,  224,  215,  225,  225,  225,
      226,  226,  226,    0,  219,  227,  227,  227,  218,    0,

      221,    0,  220,  228,  228,  228,  229,  229,  229,    0,
        0,  223,    0,    0,  226,  230,  230,  230,  227,  225,
        0,  224,  231,  231,  231,    0,    0,  228,    0,  229,
      232,  232,  232,  233,  233,  233,  234,  234,  234,  230,
        0,  231,  235,  235,  235,  236,  236,  236,  237,  237,
      237,    0,  233,  238,  238,  238,  232,  239,  239,  239,
        0,    0,  240,  240,  240,  241,  241,  241,  242,  242,
      242,    0,    0,  234,  243,  243,  243,  238,  235,    0,
        0,  237,  244,  244,  244,  245,  245,  245,  236,    0,
      240,    0,    0,  243,    0,  239,  240,  246,  246,  246,

      240,  247,  247,  247,  248,  248,  248,  249,  249,  249,
      250,  250,  250,  251,  251,  251,    0,  245,  252,  252,
      252,  244,    0,    0,  246,  253,  253,  253,  254,  254,
      254,    0,    0,  247,    0,  249,  255,  255,  255,    0,
      248,  256,  256,  256,  258,  258,  258,  250,  257,  257,
      257,  251,  259,  259,  259,    0,  252,  260,  260,  260,
      261,  261,  261,  262,  262,  262,  254,    0,    0,  255,
        0,    0,  256,  263,  263,  263,  257,  264,  264,  264,
      259,  261,  265,  265,  265,    0,    0,  262,    0,  266,
      266,  266,  267,  267,  267,    0,    0,  260,  268,  268,

      268,  269,  269,  269,  270,  270,  270,    0,  271,  271,
      271,    0,  265,  266,    0,  264,    0,  263,  272,  272,
      272,    0,  268,  273,  273,  273,  274,  274,  274,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  269,  271,  276,  276,  277,  277,
      277,  278,  278,  278,  279,  279,  280,  280,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,

      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/config_parser/lexer.l"
#line 2 "src/config_parser/lexer.l"
	#include <stdio.h>
	//DELETE THIS SHIT ON MAC
	//IM SERIOUS
	typedef struct Config Config;
	#include "ConfigParser.hpp"
	int yylex(void);
#define YY_NO_INPUT 1
#line 904 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 13 "src/config_parser/lexer.l"


#line 1087 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 276 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1559 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 15 "src/config_parser/lexer.l"
return ACCLOG;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 16 "src/config_parser/lexer.l"
return ALLOWED_METHODS;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 17 "src/config_parser/lexer.l"
return AUTOINDEX;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 18 "src/config_parser/lexer.l"
return CGI_INTERPRETER;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 19 "src/config_parser/lexer.l"
return CGI_TIMEOUT;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 20 "src/config_parser/lexer.l"
return CLIENT_MAX_BODY_SIZE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 21 "src/config_parser/lexer.l"
return DAEMON;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 22 "src/config_parser/lexer.l"
return ERRLOG;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 23 "src/config_parser/lexer.l"
return ERROR_PAGE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 24 "src/config_parser/lexer.l"
return IDLE_TIMEOUT;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 25 "src/config_parser/lexer.l"
return INDEX;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 26 "src/config_parser/lexer.l"
return KA_TIMEOUT;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 27 "src/config_parser/lexer.l"
return REQUEST_LENGTH;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 28 "src/config_parser/lexer.l"
return URI_LENGTH;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 29 "src/config_parser/lexer.l"
return LISTEN;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 30 "src/config_parser/lexer.l"
return LOCATION;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 31 "src/config_parser/lexer.l"
return REDIRECTION; 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 32 "src/config_parser/lexer.l"
return ROOT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 33 "src/config_parser/lexer.l"
return SERVER;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 34 "src/config_parser/lexer.l"
return SERVER_NAME;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 35 "src/config_parser/lexer.l"
return KA_TIME;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 36 "src/config_parser/lexer.l"
return KA_PROBES;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 37 "src/config_parser/lexer.l"
return KA_INTERVAL;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 38 "src/config_parser/lexer.l"
return MIMETYPES;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 39 "src/config_parser/lexer.l"
return URI;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 40 "src/config_parser/lexer.l"
return QUOTE;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 41 "src/config_parser/lexer.l"
return OBRACE;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 42 "src/config_parser/lexer.l"
return EBRACE;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 43 "src/config_parser/lexer.l"
return SEMICOLON;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 44 "src/config_parser/lexer.l"
return COLON;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 45 "src/config_parser/lexer.l"
return EQUALS;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 46 "src/config_parser/lexer.l"
return TILDE;
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 47 "src/config_parser/lexer.l"
/* пропускаем концы строк */;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 48 "src/config_parser/lexer.l"
/* пропускаем пробелы */;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 49 "src/config_parser/lexer.l"
{ yylval.number=!strcmp(yytext,"on"); return STATE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 50 "src/config_parser/lexer.l"
{ yylval.string=strdup(yytext); return HTTP_METHOD; }	
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 51 "src/config_parser/lexer.l"
{ yylval.string=strdup(yytext);	return FILESIZE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 52 "src/config_parser/lexer.l"
{ yylval.string=strdup(yytext); return IP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 53 "src/config_parser/lexer.l"
{ yylval.number=atoi(yytext); 	return NUMBER; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 54 "src/config_parser/lexer.l"
{ yylval.string=strdup(yytext); return WORD; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 55 "src/config_parser/lexer.l"
{ yylval.string=strdup(yytext); return PATH; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 56 "src/config_parser/lexer.l"
{ yylval.string=strdup(yytext); return URL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 57 "src/config_parser/lexer.l"
ECHO;
	YY_BREAK
#line 1386 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 276 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 276 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 275);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 57 "src/config_parser/lexer.l"



